# Building -------------------------------------------------------------------------------------------------------------
[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

# Project settings -----------------------------------------------------------------------------------------------------
[project]
name = "eco-amazon-electronics"
version = "0.1.0"
description = "Multi-objective recommender system for Amazon electronics, balancing user preferences with agent-derived carbon footprint information for sustainable e-commerce."
readme = "README.md"
requires-python = "==3.14.4"

# Required dependencies ------------------------------------------------------------------------------------------------
dependencies = [
    "kmeans-pytorch==0.3",
    "numpy==2.4.4",
    "pandas==3.0.2",
    "pyyaml==6.0.1",
    "python-dotenv==1.2.1",
    "ray==2.55.1",
    "ray[default]==2.55.1",
    "ray[tune]==2.55.1",
    "recbole==1.2.0",
    "torch==2.11.0",
    "tqdm==4.67.3"
]

# Optional dependencies ------------------------------------------------------------------------------------------------
[project.optional-dependencies]
dev = [
    "dvc[s3]==3.67.1",
    "pre-commit==4.6.0",
    "ruff==0.15.12"
]

# Other project settings -----------------------------------------------------------------------------------------------
[project.urls]
"Source" = "https://github.com/michelepatella/eco-amazon-electronics"

# Tools settings -------------------------------------------------------------------------------------------------------
[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["ALL"]
extend-select = ["D"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.pydocstyle]
convention = "google"
