dataset:
  # ------------------------------------------------------------------------------------
  # Description: Name of the Amazon Reviews'23 dataset to use
  # Type: str
  # Constraints: Must be one of the supported datasets (see src/const.py,
  #              SUPPORTED_DATASETS)
  # ------------------------------------------------------------------------------------
  name: "electronics"
